patches/next/mm/damon/Kconfig: depends kunit tests on KUNIT=y
DAMON kunit tests are static-built, and depends on KUNIT.  Meanwhile,
KUNIT can be built as module.  In the case, build fails since DAMON
kunit tests in kernel tries to use symbol of kunit module, like below.

    mm/damon/tests/core-kunit.h:394:(.text+0x9c5): undefined reference to `kunit_binary_assert_format'

It is caused by commit 06463781fa14 ("mm/damon/Kconfig: select DAMON
modules to test when test config is set") which changed the dependency
of DAMON kunit tests from KUNIT=y to KUNIT.  Restore the dependencies to
KUNIT=y.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407202132.JxTrdrIU-lkp@intel.com/
Signed-off-by: SeongJae Park <sj@kernel.org>